cors:
  originPatterns: http://leomac00.com,http://localhost:8080,http://localhost:3000
file:
  upload-dir: /Projects/upload-dir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
server:
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2KB
        max-file-size: 200MB
        max-request-size: 215MB
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**, /auth
  swagger-ui:
    use-root-path: true